### ISSUE TITLE
Updating current maintainers

### ISSUE THREAD

**Issue by rolker** [apl-ocean-engineering/marine_msgs#52]
The repo's README file has @lauralindzey, @CaptKrasno, @bsb808, and @rolker listed as current maintainers.

The package.xml files are only listing Laura but I will add myself to those files.

Should we keep a list of maitainers in the README file? If so, should it reflect the maintainers in the package.xml files?

More importantly, who wants to stay on as part of the marine_msgs maintenace team?

**Comment by lauralindzey** [comment]
I think it's OK for there to be a difference between core team listed in the README and maintainers in the package.xml

As I understand it, package.xml means "these people get emailed when the ROS build farm breaks", while I'd say the README acknowledges contributions + people who may be involved in discussions about message changes/additions.

**Comment by rolker** [comment]
Sounds good. I've updated the package.xml files and left the README file as is.
